name: Publish Test Coverage Report

on:
  push:
    branches: [ "main" ]

jobs:
  publish-code-coverage-report:
    name: JAVA 
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.head_commit.message), 'skip ci')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Upload coverage report
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        # Set CC_TEST_REPORTER_ID as secret of your repo
        CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
      with:
        # The report file must be there, otherwise Code Climate won't find it
        coverageCommand: mvn test
        coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
